#!/bin/sh

# A script for generating release tarballs and template release notes
# Just run it, the result will popup in /tmp and it'll tell you the files
# BUG: in the release note, if you tag as a + you're screwed, but anyway
# This script is meant for balance rcs and stable releases

# Call it as sh ./create_release to avoid cd'ing elsewhere.

# OPTIONS: (only for local deployment, use no options for releases)
# --keep-preload
# 	will keep the preloading directive in HTML files
# --gzip
# 	precompress all HTML/CSS/JS/JSON files as <file>.gz
# 	Useful only if your server has precompression enabled
# --one-css
# 	fuse all CSS to a single css/style.css
# --minify
# 	minifies everything. Requires a recent version of it.
# 	Debian 13 version won't cut it.
# --mascal
# 	do the all of them

which composer >/dev/null
if test $? != 0; then
	echo "COMPOSER not found, install php-composer!!!"
	exit 1
fi

KEEP_PRELOAD=
GZIP=
MINIFY=
ONE_CSS=
for arg in "$@"; do
	case "$arg" in
		--keep-preload)
			KEEP_PRELOAD=1
			echo "===> Preload is kept!"
			;;
		--gzip)
			GZIP=1
			echo "===> All pages will have a precompressed GZIP archive!"
			;;
		--mascal)
			KEEP_PRELOAD=1
			GZIP=1
			MINIFY=1
			ONE_CSS=1
			echo "===> Applying all cort.ovh optims!"
			;;
		--minify)
			which minify >/dev/null
			if test $? != 0; then
				echo "minify not found, install it!"
				exit 1
			fi
			MINIFY=1
			echo "===> Minify activated"
			;;
		--one-css)
			ONE_CSS=1
			echo "===> Using a single css for all the site"
			;;

	esac
done

# Go to repo root
cd "$(git rev-parse --show-toplevel)"

TAG=$(git tag --sort=-creatordate | awk 'NR==1')
PREVIOUS_TAG=$(git tag --sort=-creatordate | awk '/^[0-9]+\.[0-9]+\.[0-9]+$/{if (++count == 2) print}')
echo "===> Found version ${TAG}. Previous one was ${PREVIOUS_TAG}."

echo "===> Creating the necessary directories and put files"
TMPDIR=$(mktemp -d)
TARGET="${TMPDIR}/CoRT-${TAG}"
mkdir "${TARGET}"
git ls-files -z | xargs -0 -I {} cp --parents {} "${TARGET}/"

echo "===> Make source code change"
cd "${TARGET}"
# Remove all preload statements unless --keep-preload has been provided
if test -z "$KEEP_PRELOAD"; then
	echo "Removing preloading"
	sed -i '/<link rel="preload"/d' *.html
fi
if test -n "$ONE_CSS"; then
	echo "Fuse all CSS"
	cp css/style.css .
	rm css/style.css
	cat `ls css/* | sort` >> style.css
	rm css/*
	mv style.css css
	# Remove all <link> pointing to !css/style.css
	find . -name '*.html' -print0 | xargs -0 sed -i '/<link.*rel="stylesheet"/ { /href="[^"]*css\/style\.css"/!d }'
fi
# Cache bust top js and css
echo "Cache bust top js and css"
ESCAPED_VERSION=$(printf '%s' "${TAG}" | sha1sum | cut -c1-8)
find . -name '*.html' -print0 | xargs -0 sed -E -i'' 's/\.(css|js)(\?[^"]*)?">/.\1?'$ESCAPED_VERSION'">/g'
find . -name '*.js' -print0 | xargs -0 sed -E -i'' '/^[[:space:]]*import.*\.js"/s/(\.js)(\?[^"]*)?"/\.js?'$ESCAPED_VERSION'"/g'
# This cache bust is for web workers
find . -name '*.js' -print0 | xargs -0 sed -i '' -e "s/bundlereplaceme/$ESCAPED_VERSION/g"
# Put a fixed version
sed -i -E 's/(<!--VERSION-->Version: ).+/\1'"${TAG}"'/' js/menu.js


# XXX content manipulation ends here
# gzip and minify
if test -n "$MINIFY"; then
	echo "Minifying assets (may be slow)"
	find . -type f \( -name "*.css" -o -name "*.js" -o -name "*.html" -o -name "*.json" \) -exec minify -q -i {} \;
fi
if test -n "$GZIP"; then
	echo "GZIPing assets (may be slow)"
	find . -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" -o -name "*.json" \) -exec gzip -9k {} \;
fi

echo "Generating tarball"
TARBALL="/tmp/CoRT-${TAG}.tar.gz"
composer install &&
tar -czf "${TARBALL}" \
	--transform "s,^,CoRT-${TAG}/," \
	*

echo "Generating release note template..."
cat <<EOF > "${TARBALL}.release_notes.md"
## Main highlights

### Next release

No schedule.

## About

See  https://codeberg.org/mascal/CoRT/src/branch/main/deploy to deploy it

To setup CoRT on managed webhosting or integrating it on your own server, use **CoRT-${TAG}.tar.gz** instead of the source code.

### Changelog


**Full Changelog**: https://codeberg.org/mascal/CoRT/compare/${PREVIOUS_TAG}...${TAG}
EOF

echo "===> Cleaning up"
rm -rf "${TMPDIR}"

echo "===> Tarball generated at ${TARBALL}"
echo "===> Template release notes generated at ${TARBALL}.release_notes.md"

