#!/bin/sh

out_yearly="dumps/`date +%Y`_events.csv"
out_history="dumps/all_events.csv"

mkdir -p dumps
sqlite3 -header -csv events.sqlite 'select datetime(date, "unixepoch") as date_utc, name, location as original_location, owner as current_owner, type from events where date_utc >= datetime(strftime("%Y") || "-01-01 00:00:00")' > $out_yearly
sqlite3 -header -csv events.sqlite 'select datetime(date, "unixepoch") as date_utc, name, location as original_location, owner as current_owner, type from events;' > $out_history
gzip -9fk $out_yearly $out_history

cat <<EOF > dumps/index.html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>CoRT warstatus dump</title>
		<style>
		html {
			background: black;
			color: white;
			padding: 1em;
		}
		body {
			margin: 1em auto;
			padding: 1em;
			max-width: 30em;
			background: #222222;
			font-family: sans-serif;
		}
		h1, p { text-align: center;}
		a { color: lightcyan; text-decoration: none; }
		a:hover { color: lightpink }
		</style>
	</head>
	<body>
		<h1>CoRT warstatus dump</h1>
		<p><i><b>Last update</b>: `date -R`</i></p>
		<ul>
		`
		for csv in dumps/*.csv; do
			f=$(basename $csv)
			echo "<li><a href=\"$f\">$f</a> (~ $(wc -l < $csv) events)</li>"
		done | sort -r
		`
		</ul>
	</body>
</html>
EOF
