name: Create Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up files with sed
        run: |
          # Remove all preload statements
          sed -i '/<link rel="preload"/d' *.html

          # Put a fixed version
          sed -i -E 's/(<!--VERSION-->Version: ).+/\1'"${{ github.ref_name }}"'/' js/menu.js
      
      - name: Create custom tarball
        run: |
          sudo apt install composer &&
          composer install &&
          tar -czf ${{ runner.temp }}/CoRT-${{ github.ref_name }}.tar.gz \
            --transform "s,^,CoRT-${{ github.ref_name }}/," \
            *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: |
            ### About
            
            This is an automated release.

            See https://github.com/mascaldotfr/CoRT/tree/main/deploy/README.md to deploy it

            To setup CoRT on managed webhosting or integrating it on your own server, use **CoRT-${{ github.ref_name }}.tar.gz** instead of the source code.

            ### Changelog
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ runner.temp }}/CoRT-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
